# Generated by Django 5.0.4 on 2024-05-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('IdPais', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUva',
            fields=[
                ('IdUva', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DenominacionOrigen',
            fields=[
                ('IdDenominacion', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('IdVino', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DenominacionOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.denominacionorigen')),
                ('TiposUvas', models.ManyToManyField(to='principal.tipouva')),
            ],
        ),
    ]
