# Generated by Django 5.0.4 on 2024-05-12 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Pais')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Uva',
            fields=[
                ('idUva', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('idDenominacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Denominacion')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.pais')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('idVino', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('precio', models.FloatField()),
                ('denominacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.denominacion')),
                ('uvas', models.ManyToManyField(to='principal.uva')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
